### ISSUE TITLE
Keyboard doesn't behave the way it does in the demo

### ISSUE THREAD

**Issue by TheGreenAirplane** [densen2014/BootstrapBlazor.OnScreenKeyboard#2]
Hello,
I have tried using your keyboard, I installed the Nuget package according to the Readme.
The resulting keyboard doesn't look or behave like the keyboard in this demo - https://blazor.app1.es/onscreenkeyboards (see picture)
![image](https://github.com/densen2014/BootstrapBlazor.OnScreenKeyboard/assets/12677130/af473efa-b40a-46d2-a915-c8e325de0bc5)
The keyboard doesn't look like in the demo, isn't anchored to the bottom, and there is no sliding animation. If I make the window smaller than full screen, it doesn't even fit in the window. The keyboard is always the same, even if numpad is selected.

Herere's my code:

```
@page "/"
@using BootstrapBlazor.Components

<PageTitle>Home</PageTitle>
<h1>Keyboard test</h1>
@code {
    string BindValue = "virtualkeyboard";
    string ClassName = "virtualkeyboard";
}

<input class="@ClassName"
       data-kioskboard-type="@KeyboardType.all.ToString()"
       data-kioskboard-specialcharacters="true"
       placeholder="全键盘" />
<input class="@ClassName"
       data-kioskboard-type="@KeyboardType.keyboard.ToString()"
       data-kioskboard-placement="@KeyboardPlacement.bottom.ToString()"
       placeholder="字母键盘" />
<input class="@ClassName"
       data-kioskboard-type="@KeyboardType.numpad.ToString()"
       data-kioskboard-placement="@(KeyboardPlacement.bottom.ToString())"
       placeholder="数字键盘" />
<OnScreenKeyboard ClassName="@ClassName" />
```
I couldn't figure out what to put in` @ClassName `(it doesn't say anywhere) so I put in "virtualkeyboard" which I found in the source code.
```
  [Parameter]
  public string ClassName { get; set; } = "virtualkeyboard";
```
Can you help me figure out what I'm doing wrong? Thank you.

**Comment by densen2014** [comment]
here ia demo page source code

https://github.com/densen2014/Densen.Extensions/blob/master/Demo/DemoShared/Pages/OnScreenKeyboards.razor

**Comment by TheGreenAirplane** [comment]
Sorry, this was my mistake (forgot to set rendermode AGAIN). This issue should be deleted.

**Comment by densen2014** [comment]
net8 static mode is a big problem：）
